config/routes.rb
Meidusa::Application.routes.draw do

  resources :products

  root 'welcome#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true, length: {minimum: 10}
  validates :price, presence: true
  validates :image_url, presence: true
  #validates_with EmailValidator
  validates :tags, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  private
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    logger.debug "products is =============#{@products.inspect}"
  end

  def new
    @product = Product.new if @product.nil?
    logger.debug "product in new is: #{@product.inspect}"
  end

  def edit
    @product = Product.find(params[:id])
  end

  #def upload
  #  uploaded_io = params[:product][:image_url]
  #  File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
  #    file.write(uploaded_io.read)
  #  end
  #end

  def update
    @product = Product.find(params[:id])
    logger.debug "the product to be updated is: -----#{@product.inspect}"
    logger.debug "the new product is: -----#{params[:product].inspect}"

    product = params[:product]
    pic = product[:image_url].original_filename if !product[:image_url].nil?

    #if @product.update(post_params)
    if @product.update({:title => product[:title], :description => product[:description],
                            :price => product[:price], :tags => product[:tags],
                            :image_url => pic})
      savePicture product
      redirect_to products_path
    else
      render :edit
    end
  end

  def create
    logger.debug "the product to be created is: -----#{params[:product].inspect}"
    product = params[:product]
    pic = product[:image_url].original_filename if !product[:image_url].nil?

    @product = Product.new({:title => product[:title], :description => product[:description],
                            :price => product[:price], :tags => product[:tags],
                            :image_url => pic})
    if @product.save
      savePicture product
      redirect_to action: 'index'
    else
      render :new
    end
  end


  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def savePicture(product)
    uploaded_io = product[:image_url]
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
  end

  # this method is unused
  def product_params
    logger.debug "parmas.require is: #{params.require(:product)}"
    params.require(:product).permit(:title, :description, :tags, :price, :image_url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Meidusa</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<div class="container">
    <h2><%= page_title %> </h2>
    <div class="create-button">
        <%= link_to t('.back'), products_path, class: 'btn btn-default col-md-offset-10' %>
    </div>
    <%= form_for @product, html: {class: 'form-horizontal'} do |f| %>
        <% if @product.errors.any? %>
            <div class="error col-sm-offset-2">
                <p><%= pluralize(@product.errors.count, t('.error_count_singular'), t('.error_count_plural')) %></p>
                <ul>
                    <% @product.errors.each_with_index do |msg, i| %>
                        <li><%= msg[1] %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <div class="form-group">
            <%= f.label :title, t('.name'), class: 'col-sm-2 control-label' %>
            <div class="col-sm-9">
                <%= f.text_field :title, class: 'form-control' %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :description, t('.description'), class: 'col-sm-2 control-label' %>
            <div class="col-sm-9">
                <%= f.text_area :description, class: 'form-control' %>
            </div>
        </div>

        <div class="form-group file-upload">
            <%= f.label :image_url, t('.image_url'), class: 'col-sm-2 control-label' %>
            <div class="col-sm-9">
                <%= f.file_field :image_url, class: 'filestyle' %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :price, t('.price'), class: 'col-sm-2 control-label' %>
            <div class="col-sm-9">
                <%= f.text_field :price, class: 'form-control' %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :tags, t('.tags'), class: 'col-sm-2 control-label' %>
            <div class="col-sm-9">
                <%= f.text_field :tags, class: 'form-control' %>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-9">
                <%= f.submit t('.submit'), class: 'btn btn-primary btn-lg' %>
            </div>
        </div>
    <% end %>
</div>

app/views/products/edit.html.erb
<% page_title = t '.page_title' %>
<%= render partial: "form", locals: {page_title: page_title} %>

app/views/products/index.html.erb
<h2><%= t('.page_title') %></h2>

<div class="row create-button">
    <%= link_to t('.create'), new_product_path, class: 'btn btn-default col-md-offset-10' %>
</div>

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th><%= t('.number') %></th>
            <th><%= t('.name') %></th>
            <th><%= t('.image_url') %></th>
            <th><%= t('.description') %></th>
            <th><%= t('.price') %></th>
            <th><%= t('.operation') %></th>
        </tr>
        </thead>
        <tbody>
        <% @products.each_with_index do |product, index| %>
            <tr>
                <td><%= index + 1 %></td>
                <td><%= product.title %></td>
                <td><%= image_tag '/uploads/'+product.image_url, :size => "230x150" %></td>
                <td><%= product.description %></td>
                <td><%= product.price %></td>
                <td><%= link_to t('.edit'), edit_product_path(product), class: 'btn btn-default btn-sm'
                    %>
                    <%= link_to t('.delete'), product_path(product), class: 'btn btn-default btn-sm',
                                method: :delete, data: {confirm: t('.confirm_message')} %>
                </td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/products/new.html.erb
<% page_title = t '.page_title' %>
<%= render partial: "form", locals: {page_title: page_title} %>

app/views/welcome/index.html.erb
<h2 class="page-title"><%= t :hello_world %></h2>
<h2 class="page-title-mobile">
    <p></p><%= t :hello %></p>
    <p></p><%= t :world %></p>
</h2>

<div class="row create-button">
    <%= link_to t('click_me'), products_path, class: 'click-me col-md-offset-10' %>
</div>

<div class="world-clock">
    <ul class="clock">
      <li>
          <canvas class="CoolClock:securephp:130::8:showDigital:logClock"></canvas>
          <p><%= t :beijing %></p>
      </li>
      <li>
          <canvas class="CoolClock:Disc:130::-8:showDigital:logClock"></canvas>
          <p><%= t :sanF %></p>
      </li>
      <li>
          <canvas class="CoolClock:Tor:130::11:showDigital:logClock"></canvas>
          <p><%= t :sydney %></p>
      </li>
      <li>
          <canvas class="CoolClock:machine:130::5.3:showDigital:logClock"></canvas>
          <p><%= t :bangalore %></p>
      </li>
      <li>
          <canvas class="CoolClock:watermelon:130::0:showDigital:logClock"></canvas>
          <p><%= t :london %></p>
      </li>
      <li>
          <canvas class="CoolClock:Lev:130::1:showDigital:logClock"></canvas>
          <p><%= t :berlin %></p>
      </li>
    </ul>
</div>